# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
